/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERVER_H_RPCGEN
#define _SERVER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct message {
	char *message;
	int code;
};
typedef struct message message;

struct request {
	char *first;
	char *second;
};
typedef struct request request;

#define SERVER 0x2fffffff
#define SERVER_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define sum 1
extern  int * sum_1(int *, CLIENT *);
extern  int * sum_1_svc(int *, struct svc_req *);
#define print_message 2
extern  int * print_message_1(struct message *, CLIENT *);
extern  int * print_message_1_svc(struct message *, struct svc_req *);
#define concat 3
extern  char ** concat_1(struct request *, CLIENT *);
extern  char ** concat_1_svc(struct request *, struct svc_req *);
#define increment 4
extern  int * increment_1(void *, CLIENT *);
extern  int * increment_1_svc(void *, struct svc_req *);
#define get 5
extern  int * get_1(void *, CLIENT *);
extern  int * get_1_svc(void *, struct svc_req *);
extern int server_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sum 1
extern  int * sum_1();
extern  int * sum_1_svc();
#define print_message 2
extern  int * print_message_1();
extern  int * print_message_1_svc();
#define concat 3
extern  char ** concat_1();
extern  char ** concat_1_svc();
#define increment 4
extern  int * increment_1();
extern  int * increment_1_svc();
#define get 5
extern  int * get_1();
extern  int * get_1_svc();
extern int server_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_message (XDR *, message*);
extern  bool_t xdr_request (XDR *, request*);

#else /* K&R C */
extern bool_t xdr_message ();
extern bool_t xdr_request ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SERVER_H_RPCGEN */
