/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "server.h"

static int cpt = 0;

int *
sum_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	result = 2 * (*argp);

	return &result;
}

int *
print_message_1_svc(struct message *argp, struct svc_req *rqstp)
{
	static int  result;

  printf("%d - %s\n", argp->code, argp->message);
  result = 0;
	return &result;
}

char **
concat_1_svc(struct request *argp, struct svc_req *rqstp)
{
	static char * result;
  result = malloc(sizeof(argp->first) + sizeof(argp->second));
  strcat(result, argp->first);
  strcat(result, argp->second);
	return &result;
}

int *
increment_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;
  ++cpt;
  result = cpt;
	return &result;
}

int *
get_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

  result = cpt;

	return &result;
}
