/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "server.h"
#include <stdio.h>
#include <stdlib.h>

int cpt = 0;

int *
sum_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	result = (*argp);
	// On incrémente
	++result;
	return &result;
}

void *
print_message_1_svc(struct message *argp, struct svc_req *rqstp)
{
	static char * result;
	printf("%d - %s\n", argp->code, argp->message);
	return (void *) &result;
}

struct response *
concat_1_svc(struct request *argp, struct svc_req *rqstp)
{
	static struct response  result;

	result.resp = malloc(sizeof(argp->first) + sizeof(argp->second));
	strcat(result.resp, argp->first);
	strcat(result.resp, argp->second);
	return &result;
}

void *
increment_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	++cpt;
	return (void *) &cpt;
}
