/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "server.h"

bool_t
xdr_message (XDR *xdrs, message *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->message, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->code))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request (XDR *xdrs, request *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->first, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->second, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_response (XDR *xdrs, response *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->resp, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
